### PR TITLE
Command: "storage array" puppet type, provider and rspec test implemented

### PR DESCRIPTION
**Pull request by nidhimittalhada**

### CODE REVIEW

**Comment by nidhimittalhada** [comment]
Can someone please look at it for review?

**Comment by nidhimittalhada** [comment]
By mistake closed the branch, reopening

**Comment by hunner** [comment]
Looks good! Sorry it took so long. Looks like you have a bunch of other branches ready to go too?

**Comment by nidhimittalhada** [comment]
Thanks a lot Hunner for reviewing it, Yes we waited long for it :), and there are few more branches, i will just create PRs for them and request you to review them too. That will be really helpful as some of our customers are waiting on this ..

**Pull request merged**
