### PR TITLE
add snapshot policy

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@bmjen another one :+1:

**Comment by hunner** [comment]
:+1: backwards incompatible, but the other way probably never worked... so bugfix?

**Comment by bmjen** [comment]
I was going to ask about the backwards compatibility with pre-8.3

**Comment by tphoney** [comment]
asking in https://tickets.puppetlabs.com/browse/MODULES-2618

**Pull request merged**
